# Generated by Django 4.0.1 on 2022-02-06 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stream_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stream',
            old_name='uri',
            new_name='stream_bytes',
        ),
        migrations.RemoveField(
            model_name='stream',
            name='name',
        ),
        migrations.RemoveField(
            model_name='stream',
            name='type',
        ),
    ]
