# Generated by Django 3.2.9 on 2022-02-02 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='stream_bytes',
            field=models.CharField(max_length=1000000000000000000000000000000000000000000000000000000000),
        ),
    ]
