# Generated by Django 4.0.1 on 2022-02-06 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream_api', '0002_alter_stream_stream_bytes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='stream_bytes',
            field=models.ImageField(upload_to=''),
        ),
    ]
